.TH "Vala Panel Runner" "1"
.SH "NAME"
vala-panel-runner \(em  Vala Panel Runner is a simple graphical application launcher.
.SH "SYNOPSIS"
.PP
\fBvala-panel-runner\fR [           {\fB-h\fP  | \fB\-\-help\fP }           ]
.SH "DESCRIPTION"
.PP
This manual page documents briefly the
\fBvala-panel-runner\fR command.
.PP
This manual page was written for the Debian distribution
because the original program does not have a manual page.
.PP
\fBvala-panel-runner\fR is a program that runs an application launcher
.\" created by instant / docbook-to-man
